//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSO.Web.View {
    
    
    public partial class ViewSchme {
        
        /// <summary>
        /// lblDeathLiveUnvestedOptionFor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDeathLiveUnvestedOptionFor;
        
        /// <summary>
        /// lblDeathVestedOptionLiveTillExersideDt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDeathVestedOptionLiveTillExersideDt;
        
        /// <summary>
        /// lblDeathLiveVestedOptionsfor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDeathLiveVestedOptionsfor;
        
        /// <summary>
        /// lblDeathVestUnvestedOptionOnSepDt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDeathVestUnvestedOptionOnSepDt;
        
        /// <summary>
        /// lblResigLiveUnvestedOptionFor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblResigLiveUnvestedOptionFor;
        
        /// <summary>
        /// lblResigVestedOptionLiveTillExerciseDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblResigVestedOptionLiveTillExerciseDate;
        
        /// <summary>
        /// lblResigLiveVestedOptionfor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblResigLiveVestedOptionfor;
        
        /// <summary>
        /// lblResigVestUnvestedOptionOnSepDt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblResigVestUnvestedOptionOnSepDt;
        
        /// <summary>
        /// lblRetLiveUnVestedOptionFor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblRetLiveUnVestedOptionFor;
        
        /// <summary>
        /// lblRetVestedOptionLiveTillExerciseDt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblRetVestedOptionLiveTillExerciseDt;
        
        /// <summary>
        /// lblRetLiveVestedOptionFor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblRetLiveVestedOptionFor;
        
        /// <summary>
        /// lblRetVestUnVestedOptionSepdt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblRetVestUnVestedOptionSepdt;
    }
}
